### ISSUE TITLE
Kong DB password is exposed in docker-compose

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#237]
Kong DB password is exposed in docker-compose.  It should be generated randomly for each EdgeX install and pointed to by POSTGRES_PASSWORD_FILE, with no default.

```
  kong-db:
    image: postgres:12.1-alpine
    container_name: kong-db
    hostname: kong-db
    networks:
      edgex-network:
        aliases:
            - kong-db
    ports:
        - "5432:5432"
    environment:
        - 'POSTGRES_DB=kong'
        - 'POSTGRES_USER=kong'
        - 'POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
```

**Comment by lenny-intel** [comment]
@bnevis-i , looks like this have been fixed by injecting the password via environment variable?

```
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_POSTGRES_PASSWORD:-kong}
```

Can this issue be closed?
