### ISSUE TITLE
Postgres container (kong-db) does not specify a persistent data volume

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#294]
The Postgres container (kong-db) does not specify a persistent data volume.   Kong configuration can be lost across container restarts.

```
  kong-db:
    image: postgres:12.1-alpine
    container_name: kong-db
    hostname: kong-db
    networks:
      edgex-network:
        aliases:
            - kong-db
    ports:
        - "127.0.0.1:5432:5432"
    environment:
        - 'POSTGRES_DB=kong'
        - 'POSTGRES_USER=kong'
        - 'POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
    depends_on:
      - security-secrets-setup
```

There should be a "volume:" section above that mounts to `/var/lib/postgresql/data` (aka PGDATA)

See https://hub.docker.com/_/postgres for details

cc @brian-intel @jim-wang-intel
