### ISSUE TITLE
(Hanoi) add-device-camera.yml has incorrect service name and ports

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/developer-scripts#385]
service name and ports need to be corrected appropriately for device-camera service, instead of left overs from copying device-rest  yaml file.

```
services:
  device-camera:
    image: ${REPOSITORY}/docker-device-camera-go${ARCH}:${DEVICE_CAMERA_VERSION}
    ports:
      - "127.0.0.1:49985:49985"
```
